name: Compilar y publicar APK v1.2

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: |
          mkdir project
          unzip MusicTVLite_v1.2_GitHubReady.zip -d project

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Compilar APK
        working-directory: project/MusicTVLite_v1_2
        run: gradle assembleDebug

      - name: Preparar APK
        run: cp project/MusicTVLite_v1_2/app/build/outputs/apk/debug/app-debug.apk MusicTVLite-v1.2.apk

      - name: Publicar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.2
          name: MusicTV Lite v1.2
          files: MusicTVLite-v1.2.apk
