name: Compilar y publicar APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: |
          mkdir project
          MusicTVLite_v1.1_GitHubReady.zip

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Compilar APK
        working-directory: project
        run: gradle assembleDebug

      - name: Preparar APK
        run: cp project/app/build/outputs/apk/debug/app-debug.apk MusicTVLite.apk

      - name: Publicar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          name: MusicTV Lite v1.0
          files: MusicTVLite.apk
